version: '3.9'
services:
  test-db:
    image: postgres:latest
    env_file:
      - ./config/env/testing.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
