version: '3.9'
services:
  test-db:
    image: postgres:latest
    env_file:
      - ./config/env/testing.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jomodi_test
    ports:
      - 5433:5432
